name: Check clients.yaml

on:
  pull_request:
    paths:
      - 'clients.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Run generate.sh to update CLIENTS.md
      run: |
        go install github.com/awesome-jellyfin/clients-md-generator/cmd/generate@cb53ae2fa0a08f082525d9dd06bddbece01dca31
        generate -input clients.yaml
