name: Update README.md

on:
  push:
    branches:
      - 'main'
    paths:
      - 'clients.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Run generate.sh to update README.md
      run: |
        go install github.com/awesome-jellyfin/clients-md-generator/cmd/generate@latest
        generate -input clients.yaml -out-file clients.md

        # clear clients.md
        echo "" > CLIENTS.md
        while read p; do
          if [[ $p == "{{ CLIENTS }}" ]]; then
            cat clients.md >> README.md
          else
            echo "$p" >> README.md
          fi
        done < README.template.md

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md" --allow-empty || exit 0
        git push
