name: Update README.md

on:
  push:
    branches:
      - 'main'
    paths:
      - 'clients.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Run generate.sh to update CLIENTS.md
      run: |
        go install github.com/awesome-jellyfin/clients-md-generator/cmd/generate@cb53ae2fa0a08f082525d9dd06bddbece01dca31
        generate -input clients.yaml -out-file generated-clients.md

        echo "" > CLIENTS.md
        while read p; do
          if [[ $p == "{{ CLIENTS }}" ]]; then
            cat generated-clients.md >> CLIENTS.md
          else
            echo "$p" >> CLIENTS.md
          fi
        done < assets/clients/CLIENTS.template.md

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CLIENTS.md
        git commit -m "Update CLIENTS.md" --allow-empty || exit 0
        git push
